export const SET_CHANNELS = 'CHANNELS/SET_CHANNELS';
export const SET_CHANNEL = 'CHANNELS/SET_CHANNEL';
export const CREATE_CHANNEL = 'CHANNELS/CREATE_CHANNEL';
export const ENTER_CHANNEL = 'CHANNELS/ENTER_CHANNEL';
export const LOADING_CHANNELS_START = 'CHANNELS/LOAD_CHANNELS_START';
export const LOADING_CHANNELS_FINISH = 'CHANNELS/LOAD_CHANNELS_FINISH';
