export const CREATE_USER = 'USER/CREATE_USER';
export const CREATE_USER_FAILURE = 'USER/CREATE_USER_FAILURE';
export const CREATE_USER_SUCCESS = 'USER/CREATE_USER_SUCCESS';
export const SET_USER = 'USER/SET_USER';
export const UNSET_USER = 'USER/UNSET_USER';
export const FETCH_USER = 'USER/FETCH_USER';
export const FETCH_USER_FAILURE = 'USER/FETCH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'USER/FETCH_USER_SUCCESS';
