export const SET_USER = 'USER/SET_USER';
export const FETCH_USER = 'USER/FETCH_USER';
export const FETCH_USER_FAILURE = 'USER/FETCH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'USER/FETCH_USER_SUCCESS';
export const GET_USER_LOGIN_DATA = 'USER/GET_USER_LOGIN_DATA';

