export const CREATE_USER = 'USER/CREATE_USER';
export const SET_USER = 'USER/SET_USER';
export const GET_USER_CHANNELS = 'USER/GET_USER_CHANNELS';
export const UNSET_USER = 'USER/UNSET_USER';
export const FETCH_USER = 'USER/FETCH_USER';
